package com.rafaelswitala.mediguard.ui.localization

/**
 * Zentrale Texte für Deutsch und Englisch (100+ Zeichenfolgen).
 */

import androidx.compose.runtime.staticCompositionLocalOf
import com.rafaelswitala.mediguard.data.settings.AppLanguage

data class AppStrings(
    val appName: String,
    val home: String,
    val medications: String,
    val history: String,
    val settings: String,
    val addMedication: String,
    val editMedication: String,
    val noReminders: String,
    val noRemindersBody: String,
    val createMedicationNow: String,
    val medicationName: String,
    val dosage: String,
    val unit: String,
    val notes: String,
    val durationDays: String,
    val treatmentLimitDoses: String,
    val tabletsLeft: String,
    val remainingVolume: String,
    val dosePerIntake: String,
    val doseQuantity: String,
    val medicationForm: String,
    val treatment: String,
    val ongoing: String,
    val limited: String,
    val supplyAlert: String,
    val alertAt: String,
    val reminderType: String,
    val save: String,
    val update: String,
    val delete: String,
    val edit: String,
    val view: String,
    val details: String,
    val close: String,
    val remove: String,
    val cancel: String,
    val confirmDeleteTitle: String,
    val confirmDeleteBody: String,
    val lowSupplyTitle: String,
    val lowSupplyBody: String,
    val restock: String,
    val newStock: String,
    val saveStock: String,
    val noHistory: String,
    val adherence: String,
    val takenNow: String,
    val dueNow: String,
    val nextIntakes: String,
    val noDueMedication: String,
    val markGroupTaken: String,
    val scheduled: String,
    val taken: String,
    val status: String,
    val theme: String,
    val language: String,
    val light: String,
    val dark: String,
    val system: String,
    val english: String,
    val german: String,
    val alarmSound: String,
    val alertMode: String,
    val alertModeAlarm: String,
    val alertModeSilentNotification: String,
    val alertModeSoundNotification: String,
    val selectedSound: String,
    val chooseSound: String,
    val defaultSound: String,
    val exactAlarmPermission: String,
    val exactAlarmPermissionBody: String,
    val allowExactAlarms: String,
    val notificationMedicationReminder: String,
    val notificationMedicationGroupReminder: String,
    val notificationUnlockDetails: String,
    val notificationPleaseTake: String,
    val notificationMultipleIntro: String,
    val snooze: String,
    val changeTimeOnce: String,
    val stopAlarm: String,
    val exactTime: String,
    val timeRange: String,
    val dayPeriod: String,
    val interval: String,
    val weekly: String,
    val timesExample: String,
    val from: String,
    val to: String,
    val intervalHours: String,
    val startTime: String,
    val weeklyTime: String,
    val approximatePeriods: String,
    val dayPeriodSettings: String,
    val dayPeriodSettingsHint: String,
    val dayPeriodGapError: String,
    val invalidTime: String,
    val validationHint: String,
    val stock: String,
    val durationOngoingHint: String,
    val limitedByDaysOrDoses: String,
    val limitByDays: String,
    val limitByDoses: String,
    val schedules: String,
    val noSchedules: String,
    val selectedCount: String,
    val deleteSelected: String,
    val confirmDeleteSelectedTitle: String,
    val confirmDeleteSelectedBody: String,
    val statusPending: String,
    val statusConfirmed: String,
    val statusMissed: String,
    val statusSnoozed: String,
    val groupTogetherTitle: String,
    val groupTogetherBody: String,
    val groupTogetherConfirm: String,
    val groupTogetherDecline: String,
    val pickUnifiedTime: String,
    val group: String
)

val EnglishStrings = AppStrings(
    appName = "MediGuard",
    home = "Home",
    medications = "Medications",
    history = "History",
    settings = "Settings",
    addMedication = "Add medication",
    editMedication = "Edit medication",
    noReminders = "No reminders yet",
    noRemindersBody = "Add your first medication reminder.",
    createMedicationNow = "Create medication now",
    medicationName = "Medication name",
    dosage = "Dosage",
    unit = "Unit",
    notes = "Notes",
    durationDays = "Duration (days)",
    treatmentLimitDoses = "Total doses (pieces)",
    tabletsLeft = "Tablets left",
    remainingVolume = "Volume left",
    dosePerIntake = "Dose per intake (ml)",
    doseQuantity = "Amount per intake",
    medicationForm = "Medication form",
    treatment = "Treatment",
    ongoing = "Ongoing",
    limited = "Limited",
    supplyAlert = "Supply alert",
    alertAt = "Alert at",
    reminderType = "Reminder type",
    save = "Save reminder",
    update = "Update reminder",
    delete = "Delete",
    edit = "Edit",
    view = "View",
    details = "Details",
    close = "Close",
    remove = "Remove",
    cancel = "Cancel",
    confirmDeleteTitle = "Delete medication?",
    confirmDeleteBody = "This removes the medication, its reminders and related history.",
    lowSupplyTitle = "Low supply",
    lowSupplyBody = "needs refill soon",
    restock = "Restock",
    newStock = "Amount to add",
    saveStock = "Save stock",
    noHistory = "No intake history yet",
    adherence = "Adherence",
    takenNow = "Taken now",
    dueNow = "Due now",
    nextIntakes = "Next",
    noDueMedication = "No medication is due right now.",
    markGroupTaken = "Mark as taken",
    scheduled = "Scheduled",
    taken = "Taken",
    status = "Status",
    theme = "Theme",
    language = "Language",
    light = "Light",
    dark = "Dark",
    system = "System",
    english = "English",
    german = "German",
    alarmSound = "Alarm sound",
    alertMode = "Reminder mode",
    alertModeAlarm = "Alarm",
    alertModeSilentNotification = "Silent notification",
    alertModeSoundNotification = "Notification + sound",
    selectedSound = "Selected sound",
    chooseSound = "Choose sound",
    defaultSound = "System default",
    exactAlarmPermission = "Exact alarms",
    exactAlarmPermissionBody = "Android may require exact-alarm access for punctual reminders.",
    allowExactAlarms = "Allow exact alarms",
    notificationMedicationReminder = "Time for your medication!",
    notificationMedicationGroupReminder = "Medication reminders",
    notificationUnlockDetails = "Unlock your device to see details.",
    notificationPleaseTake = "Please take",
    notificationMultipleIntro = "Please take these medications now:",
    snooze = "Snooze",
    changeTimeOnce = "Change time",
    stopAlarm = "Stop alarm",
    exactTime = "Daily",
    timeRange = "Time range",
    dayPeriod = "Time of day",
    interval = "Interval",
    weekly = "Weekday selection",
    timesExample = "Times, e.g. 08:00, 20:00",
    from = "From",
    to = "To",
    intervalHours = "Interval in hours",
    startTime = "Start time",
    weeklyTime = "Weekly time",
    approximatePeriods = "Approximate periods",
    dayPeriodSettings = "Time-of-day ranges",
    dayPeriodSettingsHint = "Define when morning, noon, afternoon, evening and night apply. All 24 hours must be covered.",
    dayPeriodGapError = "Gaps in coverage:",
    invalidTime = "Enter valid times in HH:mm format.",
    validationHint = "Enter medication, dosage and a valid reminder time.",
    stock = "Stock",
    durationOngoingHint = "No end date is needed for ongoing medication.",
    limitedByDaysOrDoses = "Choose one limit: duration or total dose count.",
    limitByDays = "Duration",
    limitByDoses = "Total doses",
    schedules = "Schedules",
    noSchedules = "No schedules",
    selectedCount = "selected",
    deleteSelected = "Delete selected",
    confirmDeleteSelectedTitle = "Delete selected medications?",
    confirmDeleteSelectedBody = "This removes the selected medications, their reminders and related history.",
    statusPending = "Pending",
    statusConfirmed = "Confirmed",
    statusMissed = "Missed",
    statusSnoozed = "Snoozed",
    groupTogetherTitle = "Take together?",
    groupTogetherBody = "These medications are scheduled close together. Group their reminders?",
    groupTogetherConfirm = "Yes, group",
    groupTogetherDecline = "No, keep separate",
    pickUnifiedTime = "Shared intake time",
    group = "Group"
)

val GermanStrings = EnglishStrings.copy(
    home = "Start",
    medications = "Medizin",
    history = "Verlauf",
    settings = "Optionen",
    addMedication = "Medikament hinzufügen",
    editMedication = "Medikament bearbeiten",
    noReminders = "Noch keine Erinnerungen",
    noRemindersBody = "Fügen Sie Ihre erste Medikamentenerinnerung hinzu.",
    createMedicationNow = "Jetzt Medikation erstellen",
    medicationName = "Medikamentenname",
    dosage = "Dosierung",
    unit = "Einheit",
    notes = "Notizen",
    durationDays = "Dauer in Tagen",
    treatmentLimitDoses = "Gesamtstückzahl",
    tabletsLeft = "Tabletten übrig",
    remainingVolume = "Menge übrig",
    dosePerIntake = "Menge pro Einnahme (ml)",
    doseQuantity = "Menge pro Einnahme",
    medicationForm = "Darreichungsform",
    treatment = "Behandlung",
    ongoing = "Dauerhaft",
    limited = "Begrenzt",
    supplyAlert = "Nachschub-Hinweis",
    alertAt = "Hinweis ab",
    reminderType = "Erinnerungsart",
    save = "Erinnerung speichern",
    update = "Erinnerung aktualisieren",
    delete = "Löschen",
    edit = "Bearbeiten",
    view = "Ansehen",
    details = "Details",
    close = "Schließen",
    remove = "Entfernen",
    cancel = "Abbrechen",
    confirmDeleteTitle = "Medikament löschen?",
    confirmDeleteBody = "Dadurch werden Medikament, Erinnerungen und zugehörige Verlaufseinträge entfernt.",
    lowSupplyTitle = "Bald leer",
    lowSupplyBody = "braucht bald Nachschub",
    restock = "Nachschub",
    newStock = "Neue Menge (wird addiert)",
    saveStock = "Bestand speichern",
    noHistory = "Noch kein Einnahmeverlauf",
    adherence = "Einnahmetreue",
    takenNow = "Jetzt eingenommen",
    dueNow = "Jetzt fällig",
    nextIntakes = "Nächste",
    noDueMedication = "Aktuell ist kein Medikament fällig.",
    markGroupTaken = "Als eingenommen markieren",
    scheduled = "Geplant",
    taken = "Eingenommen",
    status = "Status",
    theme = "Design",
    language = "Sprache",
    light = "Hell",
    dark = "Dunkel",
    system = "System",
    english = "Englisch",
    german = "Deutsch",
    alarmSound = "Klingelton",
    alertMode = "Erinnerungsart",
    alertModeAlarm = "Alarm",
    alertModeSilentNotification = "Stille Benachrichtigung",
    alertModeSoundNotification = "Benachrichtigung + Ton",
    selectedSound = "Ausgewählter Ton",
    chooseSound = "Ton auswählen",
    defaultSound = "Systemstandard",
    exactAlarmPermission = "Pünktliche Alarme",
    exactAlarmPermissionBody = "Android kann eine Berechtigung für exakte Alarme verlangen.",
    allowExactAlarms = "Exakte Alarme erlauben",
    notificationMedicationReminder = "Zeit für Ihre Medikamente!",
    notificationMedicationGroupReminder = "Medikamentenerinnerungen",
    notificationUnlockDetails = "Entsperren Sie Ihr Gerät, um Details zu sehen.",
    notificationPleaseTake = "Bitte nehmen Sie jetzt",
    notificationMultipleIntro = "Bitte nehmen Sie diese Medikamente jetzt ein:",
    snooze = "Snooze",
    changeTimeOnce = "Uhrzeit ändern",
    stopAlarm = "Alarm stoppen",
    exactTime = "Täglich",
    timeRange = "Zeitfenster",
    dayPeriod = "Tageszeit",
    interval = "Intervall",
    weekly = "Wochentagauswahl",
    timesExample = "Zeiten, z. B. 08:00, 20:00",
    from = "Von",
    to = "Bis",
    intervalHours = "Intervall in Stunden",
    startTime = "Startzeit",
    weeklyTime = "Wöchentliche Zeit",
    approximatePeriods = "Ungefähre Tageszeiten",
    dayPeriodSettings = "Tageszeit-Bereiche",
    dayPeriodSettingsHint = "Legen Sie fest, wann Morgens, Mittags, Nachmittags, Abends und Nachts gelten. Alle 24 Stunden müssen abgedeckt sein.",
    dayPeriodGapError = "Lücken in der Abdeckung:",
    invalidTime = "Geben Sie gültige Uhrzeiten im Format HH:mm ein.",
    validationHint = "Geben Sie Medikament, Dosierung und eine gültige Erinnerungszeit ein.",
    stock = "Bestand",
    durationOngoingHint = "Für dauerhafte Medikamente ist kein Enddatum notwendig.",
    limitedByDaysOrDoses = "Wählen eine Begrenzung: Dauer oder Gesamtstückzahl.",
    limitByDays = "Dauer",
    limitByDoses = "Gesamtstückzahl",
    schedules = "Zeitpläne",
    noSchedules = "Keine Zeitpläne",
    selectedCount = "ausgewählt",
    deleteSelected = "Auswahl löschen",
    confirmDeleteSelectedTitle = "Ausgewählte Medikamente löschen?",
    confirmDeleteSelectedBody = "Dadurch werden die ausgewählten Medikamente, Erinnerungen und zugehörige Verlaufseinträge entfernt.",
    statusPending = "Ausstehend",
    statusConfirmed = "Bestätigt",
    statusMissed = "Verpasst",
    statusSnoozed = "Verschoben",
    groupTogetherTitle = "Gleichzeitig einnehmen?",
    groupTogetherBody = "Diese Medikamente liegen zeitlich nah beieinander. Möchten Sie ihre Erinnerungen gemeinsam anzeigen?",
    groupTogetherConfirm = "Ja, zusammenfassen",
    groupTogetherDecline = "Nein, getrennt lassen",
    pickUnifiedTime = "Gemeinsame Einnahmezeit",
    group = "Gruppe"
)

fun stringsFor(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.EN -> EnglishStrings
    AppLanguage.DE -> GermanStrings
}

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }
